language: perl

perl:
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.10"

install:
    - dzil authordeps --missing | cpanm --notest --no-skip-satisfied
    - dzil listdeps --author --missing | cpanm --notest --no-skip-satisfied

script:
    - dzil test --author --release

